export const SET_DASHBOARDS = 'SET_DASHBOARDS';
export const SET_DASHBOARD_FILTER = 'SET_DASHBOARD_FILTER';
export const SET_ACTIVE_DASHBOARD = 'SET_ACTIVE_DASHBOARD';
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
export const SET_SYSTEM_INFO = 'SET_SYSTEM_INFO';
export const SET_API_BASE_URL = 'SET_API_BASE_URL';
