import { PROGRAM_IDS } from './programIds';

export const ATTRIBUTE_IDS = {
    DV_SERIAL_NUMBER: 'QiLO2vxpmGD',
    DV_DEVICE_TYPE: 'Tzo8QQfBsak',
    DV_OWNER_ID: 'laGAvSw3jhf',
    DV_GATEWAY_DEVICE_ID: 'ZipHFPpP76i',
    DV_HARDWARE_TYPE: 'OmcU9DlPrKu',
    DV_LANGUAGE: 'u68L3OwMhqV',
    DV_TAG: 'gkiPmht2NVW',
    DV_CURRENT_PROFILE: 'WjQTTwGqyqX',
    DV_IMEI: 'IbT9IHgS5GO',
    DV_IMSI: 'GHgUr2gf29f',
    DV_SMS_NUMBER: 'n9tr5GG2Zkj',
    DV_SSH_KEY: 'IHpVLQEXUXU',
    DV_CURRENT_FIRMWARE: 'MKbkNTi07sX',
    DV_LAST_BOOTED: 'NN5r7C8NOOA',
    DV_OS_VERSION: 'WzXPdpQVajG',
    DV_REQUESTED_FIRMWARE: 'j8yLkwtrWD1',
    DV_WAN_IP: 'WAdn9DxISIi',
    DV_IP_ADDRESS: 'EmrBTdiTFmI',
    DV_LAST_TRANSMISSION_ID: 'pSUIZsCFdg5',
    DV_RESULTS_PENDING: 'aNlLXN9nEbo',
    DV_SERVICE_DATE: 'sma1WvvMYRE',
    DV_WARRANTY_EXPIRY: 'nJfU0LWm27m',
    DV_TEMPERATURE: 'Fc2ypP8I0q6',
    DV_VERSION: 'yewJIRfsHsS',
    DV_VIRTUAL_GATEWAY: 'EofngtG9vPc',
    DV_APN: 'ouA9SUIws2y',
    DV_REQUESTED_PROFILE: 'k2THsaeHpDq',
    DV_LAST_SEEN: 'Zss3gfqukHT',
};

// Only in Global instance
export const ACCOUNT_ATTRIBUTE_IDS = {
    AC_GATEWAY_AUTH_KEY: 'wFrApYY9RE2',
    AC_RESULT_AUTH_KEY: 'bUeIg4fX2Pm',
    AC_DEFAULT_NETCOM_PROFILE: 'kzAPXNisMyt',
    AC_DEFAULT_CONNECT_R1_PROFILE: 'hBFGba6EGps',
    AC_ACCOUNT_NAME: 'g5ZFgSs5Zyt',
    AC_LOGO: 'VRdGZ4ir6b9',
    AC_DEFAULT_AFINION_PROFILE: 's954CEo5JrM',
};

export const DEFAULT_PROFILE_ATTRIBUTE_IDS = {
    [PROGRAM_IDS.DV_CONNECT_GATEWAY]:
    ACCOUNT_ATTRIBUTE_IDS.AC_DEFAULT_CONNECT_R1_PROFILE,
    [PROGRAM_IDS.DV_NETCOMM_GATEWAY]:
    ACCOUNT_ATTRIBUTE_IDS.AC_DEFAULT_NETCOM_PROFILE,
};

export const TRACKED_ENTITY_TYPE_IDS = {
    PROFILE: 'VcEoOjkffns',
    ACCOUNT: 'FNjy5kQYPpX',
};
