export const OPTION_SET_IDS = {
    BAND_PRIORITY: 'X0ymOFzxaPP',
    PROFILE: 'WT3MuPwNwwh',
    APN: 'iG6IsmJyb6w',
    FIRMWARE: 'EMjEZtgDEHg',
    UPDATE_INSTANCE_FROM: 'AMILIACT5KR',
    UPDATE_INSTANCE_TO: 'L7rGiW6uWDk',
    STATUS: 'bJOdSN2z4y7',
};
